### ISSUE TITLE
国内镜像加速

### ISSUE THREAD

**Issue by APecme** [yomunsam/Jellyfin.WebDanmakuStarter#1]
大佬能不能整个国内镜像加速，我的jellyfin运行在docker下不走代理，设置了带了也不走很怪

**Comment by yomunsam** [comment]
目前设定是，可以在设置里填一个自己的地址，留空就会使用原作者的默认地址。
你看要有需求的话我们问问原作者有没有兴趣约定一个官方的镜像？

**Comment by APecme** [comment]
原作者的其他安装方式我这边好像都不太好实现，现在遇到的问题是，我在jellyfin目录里添加您的github链接后在插件中无法找到可安装的插件

**Comment by yomunsam** [comment]
哦好的，我刚刚理解错了，马上研究下😂

**Comment by yomunsam** [comment]
昂，在网络上找了一个，我这边测试是可以的：
`https://www.ghproxy.cn/https://raw.githubusercontent.com/yomunsam/Jellyfin.WebDanmakuStarter/refs/heads/master/manifest.json`
