### ISSUE TITLE
插件显示not supported

### ISSUE THREAD

**Issue by Kaiyan629** [yomunsam/Jellyfin.WebDanmakuStarter#2]
使用您的插件安装完成后无法启用，插件状态显示not supported
![image](https://github.com/user-attachments/assets/df28ca08-f734-4caf-a449-1deece9564fa)

![image](https://github.com/user-attachments/assets/9613206c-82ea-4843-a10a-73956e240df7)

jellyfin版本是nyanmisaka/jellyfin 的10.10.1，是因为这个版本问题么
![image](https://github.com/user-attachments/assets/ce7af09c-86a5-4070-b501-4a35efd5190a)

**Comment by yomunsam** [comment]
我这儿没能复现这样的问题，然后再网络上搜索了一下，似乎和运行Jellyfin的环境的dotnet版本有点关系，你看方便的话，在环境里执行一下`dotnet --version`，以及抓一下Jellyfin的Log看看？

**Comment by Kaiyan629** [comment]
查了下log
![aee7f129bdaa20e46785cbc8b324f9e](https://github.com/user-attachments/assets/28ebcc4e-28f9-4a5a-b72b-bf33ca2c884c)

我装的是nyanmisaka/jellyfin:10.10.1.0版本的jellyfin，但它好像认为我用的是10.10.3.0
所以我就更新到了10.10.3.0，还是nyanmisaka/jellyfin的版本
更新完就能正常工作了，十分感谢
![image](https://github.com/user-attachments/assets/8bd7c161-258c-424e-9c03-eab297439ac0)
